# This file is sentitive and should not push to public
base_logger                       :
  when                              : "midnight"
  interval                          : 1
  backup_count                      : 7
  log_level                         : "info"
  stream_handler_format             : "%(asctime)s - %(name)s - %(threadName)s - %(levelname)s - %(message)s"
  timed_rotating_file_handler_format: "%(asctime)s - %(name)s - %(threadName)s - %(levelname)s - %(message)s"
  log_directory                     : "./logs/"